<?php
$console['listip'] = '<span style="color:green"><b>List Banned IP\'s </b></span>';
$console['listid'] = '<span style="color:green"><b>List Banned ID\'s </b></span>';
$console['Unknown command'] = '<span style="color:orange;">Unknown command</span>';
$console['say'] = '<span style="color:magenta;"><b> say </b></span>';
$console['Console'] = '<span style="color:MediumSeaGreen;"> Console </span>';
$console['permanently'] = '<span style="color:red;"><b> permanently</b></span>'; 
$console['permanent'] = '<span style="color:red;"><b> permanent</b></span>';
$console['VAC secure mode is activated.'] = '<span style="color:green;">VAC secure mode is activated.</span>';
$console['VAC secure mode disabled.'] = '<span style="color:orange;">VAC secure mode disabled.</span>';
$console['Writing'] = '<span style="color:cyan;">Writing </span>'; 
$console['not present; '] = '<span style="color:orange;">not present; </span>';
$console['not executing.'] = '<span style="color:red;">not executing.</span>';
$console['nextlevel'] =  '<span style="color:cyan;">nextlevel</span>';
$console['Server is hibernating'] = '<span style="color:cyan;">Server is hibernating</span>';
$console['server is hibernating'] = '<span style="color:cyan;">server is hibernating</span>';
$console['Server waking up from hibernation'] = '<span style="color:cyan;">Server waking up from hibernation</span>';
$console['Executing dedicated server config file'] = '<span style="color:cyan;">Executing dedicated server config file</span>';
$console['Connection to Steam servers successful.'] = '<span style="color:cyan;">Connection to Steam servers successful.</span>';
$console['Assigned anonymous gameserver Steam ID'] = '<span style="color:cyan;">Assigned anonymous gameserver Steam ID</span>';
$console['Error loading'] = '<span style="color:red;">Error loading</span>';
$console['SOLID_VPHYSICS static prop with no vphysics model!'] = '<span style="color:magenta">SOLID_VPHYSICS static prop with no vphysics model!</span>';
$console['Public IP is'] = '<span style="color:cyan;">Public IP is</span>';
$console['Server logging enabled.'] = '<span style="color:cyan;">Server logging enabled.</span>';
$console['Log file started'] = '<span style="color:cyan;">Log file started</span>';
$console['Log file closed'] = '<span style="color:cyan;">Log file closed</span>';
$console['Server logging data to file'] = '<span style="color:cyan;">Server logging data to file</span>';
$console['Using map cycle file'] = '<span style="color:cyan;">Using map cycle file</span>';
$console['Started map'] = '<span style="color:cyan;">Started map</span>';
$console['Could not find steamerrorreporter binary. Any minidumps will be uploaded in-process'] = '<span style="color:orange;">Could not find steamerrorreporter binary. Any minidumps will be uploaded in-process<br></span>';
$console['[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.'] = '<span style="color:orange;">[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.</span>';
$console['Setting breakpad minidump AppID'] = '<span style="color:cyan;">Setting breakpad minidump AppID</span>';
$console['Set motd_text from file'] = '<span style="color:cyan;">Set motd_text from file</span>';
$console['Set motd from file'] = '<span style="color:cyan;">Set motd from file</span>';
$console['RecordSteamInterfaceCreation'] = '<span style="color:cyan;">RecordSteamInterfaceCreation</span>';
$console['ConVarRef'] = '<span style="color:cyan;">ConVarRef</span>';
$console[' doesn\'t point to an existing ConVar'] = '<span style="color:cyan;"> doesn\'t point to an existing ConVar</span>';
$console['No account token specified'] = '<span style="color:orange;">No account token specified</span>';
$console['killed'] = '<span style="color:red;">killed</span>';
$console['committed suicide'] = '<span style="color:red;">committed suicide</span>';
$console['notoriety'] = '<span style="color:tomato;">notoriety</span>';
$console['triggered combat'] = '<span style="color:dodgerblue;">triggered combat</span>';
$console['disconnected'] = '<span style="color:orange;">disconnected</span>';
$console['connected,'] = '<span style="color:green;">connected</span>';
$console['Kicked from server'] = '<span style="color:red;">Kicked from server</span>';
$console['kicked from server due high ping or unreliable connection'] = '<span style="color:tomato;">kicked from server due high ping or unreliable connection</span>';
$console['reason'] ='<span style="color:dodgerblue;">reason</span>';
$console['Disconnect by user.'] = '<span style="color:tomato;">Disconnect by user.</span>';
$console['validated'] = '<span style="color:green;">validated</span>';
$console['Steam auth ticket has been canceled'] = '<span style="color:orange;">Steam auth ticket has been canceled</span>';
$console['Client left game'] = '<span style="color:tomato;">Client left game</span>';
$console['entered the game'] = '<span style="color:cyan;">entered the game</span>';
$console['Forcing client reconnect'] = '<span style = "color:mediumseagreen;">Forcing client reconnect</span>';
$console['Dropping ClientInfo packet from client not in appropriate state'] = '<span style ="color:cyan;">Dropping ClientInfo packet from client not in appropriate state</span>';
$console['Using breakpad crash handler'] = '<span style="color:cyan;">Using breakpad crash handler</span>';
$console['Auto detecting CPU'] = '<span style="color:cyan;">Auto detecting CPU</span>';
$console['Server will auto-restart if there is a crash.'] = '<span style="color:orange;">Server will auto-restart if there is a crash.</span>';
$console['maxplayers set to'] = '<span style="color:cyan;">maxplayers set to</span>';
$console['Looking up breakpad interfaces from steamclient'] = '<span style="color:cyan;">Looking up breakpad interfaces from steamclient</span>';
$console['Using Breakpad minidump system. Version'] = '<span style="color:cyan;">Using Breakpad minidump system. Version</span>';
$console['upLoaded '] = '<span style="color:orange;">upLoaded </span>';
$console['Loaded '] = '<span style="color:cyan;">Loaded </span>';
$console[' VPK file hashes from '] = '<span style="color:cyan;"> VPK file hashes from </span>';
$console[' for pure server operation.'] = '<span style="color:cyan;"> for pure server operation.</span>';
$console['STEAM USERID'] = '<span style="color:slateblue;font-weight:bold;">STEAM USERID</span>';
$console['user_ip'] ='purple';
$console['Connection to Steam servers lost. '] = '<span style="color:orange;">Connection to Steam servers lost. </span>';
$console['for rcon hacking attempts'] = '<span style="color:orange;">for rcon hacking attempts</span>';
$console['Banning'] = '<span style="color:red;">Banning</span>'; 
$console['Attempted to create unknown entity type'] = '<span style="color:orange;">Attempted to create unknown entity type</span>';
$console['Can\'t init'] = '<span style="color:red;">Can\'t init</span>';
$console['Couldn\'t open'] = '<span style="color:red;">Couldn\'t open</span>';
$console['was not found'] = '<span style="color:red;">was not found</span>';
$console['coop'] = '<span style="color:cyan;">coop</span>';
$console['deathmatch'] = '<span style="color:cyan;">deathmatch</span>';
$console['SV_ActivateServer'] = '<span style="color:cyan;">SV_ActivateServer</span>';
?>
