<?php
/*********************************\ 
SETTINGS v1.0.18.1&psi;
 do not edit this file ! use admin cp unless told otherwise
\*********************************/
$settings['logo'] = "/img/logo.png";
$settings['gamelocation'] = "/user/games";
$settings['adminemail'] = "someone@somewhere.co.uk";
$settings['server_tz'] = "Europe/London";
$settings['paypal_email'] = "someone@somewhere.co.uk";
$settings['siteclosed'] = "0"; //block access to the site  if required
$settings['siteclosed_url'] = "/closed.html"; // return this url instead
$settings['pwdlen'] = "8"; // minimum password length for passwords
$settings['https'] = "1"; // force https (old setting not really needed now)
$settings['url'] = "https://api.noideersoftware.co.uk";
$settings['steamkey'] = ""; // future expansion
$settings['version'] = "1.0.18.1&psi;";
$settings['SQ_TIMEOUT'] = 2;
$settings['year'] = "0";
$settings['start_year'] = "2014";
$settings['time_format'] = "h:i:s a";
$settings['date_format'] = "d/m/Y";
$settings['login'] = "1";
$settings['ip_key'] =''; // ip data key
$settings['pushbullet'] = ''; //pushbullet key
$settings['scanlog'] = 1;
$settings['log_scroll_back'] = 100; // sets log scroll back set to zero for the full log .. not recomended unless using ajaxv21 or greater
$settings['send_cors'] = 0; // send cors header instead of messing with apache or .htaccess 0 = don't send 1 = send cors header
$settings['secure'] = true; // if set to false will allow ajax to execute commands without validation  - be careful
$settings['secure_user']=''; // user name for ajax requests
$settings['secure_password']=''; // userpassword for ajax requests
?>
