<?php
/*********************************\ 
SETTINGS v1.0.18.1&psi;
 do not edit this file ! use admin cp unless told otherwise
\*********************************/
$settings['logo'] = "/img/logo.png";
$settings['gamelocation'] = "/user/games";
$settings['adminemail'] = "someone@somewhere.co.uk";
$settings['server_tz'] = "Europe/London";
$settings['paypal_email'] = "someone@somewhere.co.uk";
$settings['siteclosed'] = "0";
$settings['siteclosed_url'] = "/closed.html";
$settings['pwdlen'] = "3";
$settings['https'] = "1";
$settings['url'] = "https://somewhere.co.uk";
$settings['steamkey'] = "";
$settings['version'] = "1.0.18.1&psi;";
$settings['SQ_TIMEOUT'] = 2;
$settings['year'] = "0";
$settings['start_year'] = "2014";
$settings['time_format'] = "h:i:s";
$settings['date_format'] = "d-m-Y";
$settings['login'] = "1";
$settings['ip_key'] ='';
$settings['scanlog'] = 1;
$settings['send_cors'] = 0;
?>
