<?php
/*********************************\ 
SETTINGS v1.0.18.1&psi;
 do not edit this file ! use admin cp unless told otherwise
\*********************************/
$settings['logo'] = "/img/logo.png";
$settings['mail_message_id'] = "1";
$settings['mail_parameters'] = "";
$settings['adminemail'] = "someone@somewhere.co.uk";
$settings['server_tz'] = "Europe/London";
$settings['paypal_email'] = "someone@somewhere.co.uk";
$settings['siteclosed'] = "0";
$settings['siteclosed_url'] = "/closed.html";
$settings['sitename'] = "PHPGsm";
$settings['use_address'] = "0";
$settings['address_street'] = "";
$settings['address_city'] = "";
$settings['address_postcode'] = "";
$settings['address_phone'] = "";
$settings['pwdlen'] = "3";
$settings['https'] = "1";
$settings['url'] = "https://somewhere.co.uk";
$settings['showphp'] = "0";
$settings['steamkey'] = "";
$settings['showsidebox'] = "0";
$settings['templatecomments'] = "1";
$settings['version'] = "1.0.18.1&psi;";
$settings['session'] = "1";
$settings['year'] = "0";
$settings['start_year'] = "2014";
$settings['per_page'] = "5";
$settings['ip_count'] = "4";
$settings['theme_path'] = "light";
$settings['show_device'] = "1";
$settings['time_format'] = "h:i:s";
$settings['date_format'] = "d-m-Y";
$settings['panel_url'] = "https://somewhere.co.uk:10000"; // used for server control panels e.g plesk/webmin
$settings['domain_size'] = "5.0"; // max size for software install in GB
$settings['disable_plugin'] = "0"; //  reserved for later code
$settings['login'] = "1";
?>