<?php
/*********************************\ 
SETTINGS v1.0.18.1&psi;
 do not edit this file ! use admin cp unless told otherwise
\*********************************/
$settings['logo'] = "/images/logo.png";
$settings['mail_message_id'] = "1";
$settings['mail_parameters'] = "";
$settings['adminemail'] = "jim@noideersoftware.co.uk";
$settings['server_tz'] = "Europe/London";
$settings['paypal_email'] = "jim.richardson06@btinternet.com";
$settings['avataruploadpath'] = "/uploads/avatars";
$settings['siteclosed'] = "0";
$settings['siteclosed_url'] = "/ebola.html";
$settings['sitename'] = "NoIdeer Software";
$settings['use_address'] = "0";
$settings['address_street'] = "5 Oriel House, 46 Worcester Road";
$settings['address_city'] = "Malvern";
$settings['address_postcode'] = "WR14 4AA";
$settings['address_phone'] = "07707 893449";
$settings['pwdlen'] = "3";
$settings['https'] = "1";
$settings['url'] = "https://noideersoftware.co.uk";
$settings['showphp'] = "0";
$settings['steamkey'] = "91313FE1EEF89AD8E5ED16ADBD51DF93";
$settings['showsidebox'] = "0";
$settings['templatecomments'] = "1";
$settings['forumtabs'] = "1";
$settings['version'] = "1.0.18.1&psi;";
$settings['session'] = "1";
$settings['year'] = "0";
$settings['start_year'] = "2014";
$settings['per_page'] = "5";
$settings['ip_count'] = "4";
$settings['theme_path'] = "light";
$settings['show_device'] = "1";
$settings['time_format'] = "h:i:s";
$settings['date_format'] = "d-m-Y";
$settings['panel_url'] = "https://noideersoftware.co.uk:10000";
$settings['domain_size'] = "5.0";
$settings['cookie_url'] = "/misc.php?action=27015";
$settings['disable_plugin'] = "0";
$settings['new_posts'] = "5";
$settings['olark_key'] = "9629-965-10-5349";
?>